### ISSUE TITLE
client identified by DiskPlayer not found

### ISSUE THREAD

**Issue by karl0ss** [dinofizz/diskplayer#3]
I seem really close to having this working, but for some reason, when I try to play any song I am returned with the error 

`2020/02/29 10:57:05 client identified by DiskPlayer not found`

This is my diskplayer.yaml file, XXXX replace my values -

```
spotify:
  callback_url: XXXX
  device_name: DiskPlayer
  client_id: XXXXX
  client_secret: XXXX
recorder:
  folder_path: /tmp
  filename: diskplayer.contents
  server_port: 3000
token:
   path: ./token.json

```

Can't quite work out where I am ment to define DiskPlayer as a known client?

My token.json is populated from running the auth command agaisnt the app I created in the developers console, and that seems to have worked, I don't see anything to do with "client name" in either of the calls that are made, or anywhere in the dashboard.

Hope you can help
